In [1]:
import pandas as pd

In [2]:
macro = pd.read_csv('BCI-US-UK-Dec20-Oct22.csv')

In [3]:
macro

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,USA,BCI,AMPLITUD,LTRENDIDX,M,2020-12,101.37490,NaN
1,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-01,101.52170,NaN
2,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-02,101.78390,NaN
3,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-03,101.99870,NaN
4,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-04,101.89490,NaN
5,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-05,101.75250,NaN
6,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-06,101.60990,NaN
7,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-07,101.51820,NaN
8,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-08,101.54950,NaN
9,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-09,101.64180,NaN
10,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-10,101.65730,NaN
11,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-11,101.55980,NaN
12,USA,BCI,AMPLITUD,LTRENDIDX,M,2021-12,101.33090,NaN
13,USA,BCI,AMPLITUD,LTRENDIDX,M,2022-01,101.13580,NaN
14,USA,BCI,AMPLITUD,LTRENDIDX,M,2022-02,101.01340,NaN
15,USA,BCI,AMPLITUD,LTRENDIDX,M,2022-03,100.82510,NaN
16,USA,BCI,AMPLITUD,LTRENDIDX,M,2022-04,100.60130,NaN
17,USA,BCI,AMPLITUD,LTRENDIDX,M,2022-05,100.39370,NaN
18,USA,BCI,AMPLITUD,LTRENDIDX,M,2022-06,100.11760,NaN
19,USA,BCI,AMPLITUD,LTRENDIDX,M,2022-07,99.91658,NaN
20,USA,BCI,AMPLITUD,LTRENDIDX,M,2022-08,99.74365,NaN
21,USA,BCI,AMPLITUD,LTRENDIDX,M,2022-09,99.51750,NaN
22,USA,BCI,AMPLITUD,LTRENDIDX,M,2022-10,99.29535,NaN
23,GBR,BCI,AMPLITUD,LTRENDIDX,M,2020-12,98.49242,NaN
24,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-01,98.45616,NaN
25,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-02,99.56746,NaN
26,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-03,101.37630,NaN
27,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-04,102.80670,NaN
28,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-05,103.95220,NaN
29,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-06,104.62970,NaN
30,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-07,104.92060,NaN
31,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-08,104.82650,NaN
32,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-09,104.88030,NaN
33,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-10,105.16000,NaN
34,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-11,105.44710,NaN
35,GBR,BCI,AMPLITUD,LTRENDIDX,M,2021-12,105.42520,NaN
36,GBR,BCI,AMPLITUD,LTRENDIDX,M,2022-01,105.15190,NaN
37,GBR,BCI,AMPLITUD,LTRENDIDX,M,2022-02,104.78520,NaN
38,GBR,BCI,AMPLITUD,LTRENDIDX,M,2022-03,104.41590,NaN
39,GBR,BCI,AMPLITUD,LTRENDIDX,M,2022-04,104.01940,NaN
40,GBR,BCI,AMPLITUD,LTRENDIDX,M,2022-05,103.78450,NaN
41,GBR,BCI,AMPLITUD,LTRENDIDX,M,2022-06,103.04740,NaN
42,GBR,BCI,AMPLITUD,LTRENDIDX,M,2022-07,102.03950,NaN
43,GBR,BCI,AMPLITUD,LTRENDIDX,M,2022-08,100.99030,NaN
44,GBR,BCI,AMPLITUD,LTRENDIDX,M,2022-09,100.59030,NaN
45,GBR,BCI,AMPLITUD,LTRENDIDX,M,2022-10,100.91900,NaN

In [27]:
macro_US_UK = macro[macro['TIME'] > '2020-12'][['LOCATION', 'TIME', 'Value']]

In [38]:
macro_US_UK['TIME'] = macro_US_UK['TIME'].astype('datetime64[ns]')

In [39]:
macro_US_UK

   LOCATION       TIME      Value
1       USA 2021-01-01  101.52170
2       USA 2021-02-01  101.78390
3       USA 2021-03-01  101.99870
4       USA 2021-04-01  101.89490
5       USA 2021-05-01  101.75250
6       USA 2021-06-01  101.60990
7       USA 2021-07-01  101.51820
8       USA 2021-08-01  101.54950
9       USA 2021-09-01  101.64180
10      USA 2021-10-01  101.65730
11      USA 2021-11-01  101.55980
12      USA 2021-12-01  101.33090
13      USA 2022-01-01  101.13580
14      USA 2022-02-01  101.01340
15      USA 2022-03-01  100.82510
16      USA 2022-04-01  100.60130
17      USA 2022-05-01  100.39370
18      USA 2022-06-01  100.11760
19      USA 2022-07-01   99.91658
20      USA 2022-08-01   99.74365
21      USA 2022-09-01   99.51750
22      USA 2022-10-01   99.29535
24      GBR 2021-01-01   98.45616
25      GBR 2021-02-01   99.56746
26      GBR 2021-03-01  101.37630
27      GBR 2021-04-01  102.80670
28      GBR 2021-05-01  103.95220
29      GBR 2021-06-01  104.62970
30      GBR 2021-07-01  104.92060
31      GBR 2021-08-01  104.82650
32      GBR 2021-09-01  104.88030
33      GBR 2021-10-01  105.16000
34      GBR 2021-11-01  105.44710
35      GBR 2021-12-01  105.42520
36      GBR 2022-01-01  105.15190
37      GBR 2022-02-01  104.78520
38      GBR 2022-03-01  104.41590
39      GBR 2022-04-01  104.01940
40      GBR 2022-05-01  103.78450
41      GBR 2022-06-01  103.04740
42      GBR 2022-07-01  102.03950
43      GBR 2022-08-01  100.99030
44      GBR 2022-09-01  100.59030
45      GBR 2022-10-01  100.91900

In [29]:
snp = pd.read_csv('S&P 500 - 1Jan21 to 20Nov22.csv')

In [30]:
snp

,Date,Open,High,Low,Close,Adj Close,Volume
0,2021-01-04,3764.610107,3769.989990,3662.709961,3700.649902,3700.649902,5015000000
1,2021-01-05,3698.020020,3737.830078,3695.070068,3726.860107,3726.860107,4591020000
2,2021-01-06,3712.199951,3783.040039,3705.340088,3748.139893,3748.139893,6064110000
3,2021-01-07,3764.709961,3811.550049,3764.709961,3803.790039,3803.790039,5099160000
4,2021-01-08,3815.050049,3826.689941,3783.600098,3824.679932,3824.679932,4773040000
...,...,...,...,...,...,...,...
470,2022-11-14,3977.969971,4008.969971,3956.399902,3957.250000,3957.250000,4561930000
471,2022-11-15,4006.409912,4028.840088,3953.169922,3991.729980,3991.729980,5015310000
472,2022-11-16,3976.820068,3983.090088,3954.340088,3958.790039,3958.790039,4165320000
473,2022-11-17,3919.260010,3954.330078,3906.540039,3946.560059,3946.560059,4051780000
474,2022-11-18,3966.389893,3979.889893,3935.979980,3965.340088,3965.340088,4037360000

In [35]:
# convert date to DATETIME to merge with macro data
snp['Date'] = snp['Date'].astype('datetime64[ns]')

In [47]:
# macro and snp merged
macroAndSnp = pd.merge(snp, macro_US_UK, left_on = snp['Date'].dt.month, right_on = macro_US_UK['TIME'].dt.month)

In [48]:
# unique row will be 'Date', 'LOCATION (either US or UK)'. Macro data will repeat since it is on a monthly level.
macroAndSnp

,key_0,Date,Open,High,Low,Close,Adj Close,Volume,LOCATION,TIME,Value
0,1,2021-01-04,3764.610107,3769.989990,3662.709961,3700.649902,3700.649902,5015000000,USA,2021-01-01,101.52170
1,1,2021-01-04,3764.610107,3769.989990,3662.709961,3700.649902,3700.649902,5015000000,USA,2022-01-01,101.13580
2,1,2021-01-04,3764.610107,3769.989990,3662.709961,3700.649902,3700.649902,5015000000,GBR,2021-01-01,98.45616
3,1,2021-01-04,3764.610107,3769.989990,3662.709961,3700.649902,3700.649902,5015000000,GBR,2022-01-01,105.15190
4,1,2021-01-05,3698.020020,3737.830078,3695.070068,3726.860107,3726.860107,4591020000,USA,2021-01-01,101.52170
...,...,...,...,...,...,...,...,...,...,...,...
1781,12,2021-12-29,4788.640137,4804.060059,4778.080078,4793.060059,4793.060059,2963310000,GBR,2021-12-01,105.42520
1782,12,2021-12-30,4794.229980,4808.930176,4775.330078,4778.729980,4778.729980,3124950000,USA,2021-12-01,101.33090
1783,12,2021-12-30,4794.229980,4808.930176,4775.330078,4778.729980,4778.729980,3124950000,GBR,2021-12-01,105.42520
1784,12,2021-12-31,4775.209961,4786.830078,4765.750000,4766.180176,4766.180176,2677820000,USA,2021-12-01,101.33090
1785,12,2021-12-31,4775.209961,4786.830078,4765.750000,4766.180176,4766.180176,2677820000,GBR,2021-12-01,105.42520